package views;

/**
 *
 * @author kelvincitopkmz
 */
public class AgregarPedidoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgregarPedidoView
     */
    private controllers.AgregarPedidoViewController controller;
    private controllers.DashboardViewController dashboardController;
    private javax.swing.JFrame parentFrame;

    public AgregarPedidoView() {
        initComponents();
        controller = new controllers.AgregarPedidoViewController();
        controller.initialize();
        inicializarComboSKU();
        inicializarComboTipoEnvio();
    }

    // 3. Métodos para establecer referencias
    public void setDashboardController(controllers.DashboardViewController dashboardController) {
        this.dashboardController = dashboardController;
        if (controller != null) {
            controller.setDashboardController(dashboardController);
        }
    }

    public void setParentFrame(javax.swing.JFrame frame) {
        this.parentFrame = frame;
    }

    /**
     * Inicializa el combo de tipo de envío usando el enum
     */
    private void inicializarComboTipoEnvio() {
        tipoEnvioCombo.removeAllItems();
        tipoEnvioCombo.addItem("Seleccionar...");

        // ✅ Usar el enum para llenar el combo
        for (models.TipoEnvio tipo : models.TipoEnvio.values()) {
            tipoEnvioCombo.addItem(tipo.getDescripcion());
        }
    }

// 4. Método para inicializar el combo de SKU
    private void inicializarComboSKU() {
        skuProductoVentasCombo.removeAllItems();
        skuProductoVentasCombo.addItem("Seleccionar...");

        // Obtener productos del controller
        java.util.List<models.Producto> productos = controller.obtenerProductos();

        for (models.Producto p : productos) {
            skuProductoVentasCombo.addItem(p.getSku());
        }

        System.out.println("Combo SKU inicializado con " + productos.size() + " productos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        dniField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        celularField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        skuProductoVentasCombo = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        cantidadProductoVentasField = new javax.swing.JSpinner();
        registrarPedidoButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        tipoEnvioCombo = new javax.swing.JComboBox<>();

        jLabel12.setText("DNI");

        dniField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniFieldActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Agregar datos del cliente");

        jLabel13.setText("Nombre");

        nombreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreFieldActionPerformed(evt);
            }
        });

        jLabel16.setText("Celular");

        celularField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celularFieldActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Agregar datos del producto");

        jLabel11.setText("SKU");

        skuProductoVentasCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skuProductoVentasComboActionPerformed(evt);
            }
        });

        jLabel17.setText("Cantidad");

        registrarPedidoButton.setText("Registrar pedido");
        registrarPedidoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarPedidoButtonActionPerformed(evt);
            }
        });

        backButton.setText("Volver");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel18.setText("Tipo de envío");

        tipoEnvioCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoEnvioComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel16))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dniField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(celularField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(skuProductoVentasCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cantidadProductoVentasField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel15)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(37, 37, 37)
                                .addComponent(tipoEnvioCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(registrarPedidoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel14)
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dniField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(celularField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(skuProductoVentasCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cantidadProductoVentasField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tipoEnvioCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(registrarPedidoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dniFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniFieldActionPerformed

    private void nombreFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreFieldActionPerformed

    private void celularFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celularFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celularFieldActionPerformed

    private void skuProductoVentasComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skuProductoVentasComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_skuProductoVentasComboActionPerformed

    private void registrarPedidoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarPedidoButtonActionPerformed

        // Validar que el controller esté inicializado
        if (controller == null) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Error: Controller no inicializado",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // Obtener valores de los campos
        String dni = dniField.getText();
        String nombre = nombreField.getText();
        String celular = celularField.getText();
        String sku = (String) skuProductoVentasCombo.getSelectedItem();
        int cantidad = (Integer) cantidadProductoVentasField.getValue();
        String tipoEnvio = (String) tipoEnvioCombo.getSelectedItem(); // ✅ Obtener tipo de envío

        // Registrar pedido
        boolean exitoso = controller.registrarPedido(dni, nombre, celular, sku, cantidad, tipoEnvio);

        if (exitoso) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Pedido registrado exitosamente",
                    "Éxito",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
            );

            // Limpiar campos
            dniField.setText("");
            nombreField.setText("");
            celularField.setText("");
            skuProductoVentasCombo.setSelectedIndex(0);
            cantidadProductoVentasField.setValue(0);
            tipoEnvioCombo.setSelectedIndex(0); // ✅ Resetear tipo de envío
            dniField.requestFocus();

            // Actualizar TODAS las tablas del dashboard
            if (dashboardController != null) {
                dashboardController.actualizarTablaVentas();
                dashboardController.actualizarTablaInventario();
                dashboardController.actualizarTablaConteoInventario();
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Error al registrar el pedido. Verifica:\n"
                    + "- Todos los campos del cliente estén llenos\n"
                    + "- Hayas seleccionado un producto\n"
                    + "- La cantidad sea mayor a 0\n"
                    + "- Haya stock disponible\n"
                    + "- Hayas seleccionado un tipo de envío",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_registrarPedidoButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:

        // Cerrar la ventana padre
        if (parentFrame != null) {
            parentFrame.dispose();
        } else {
            // Si no hay parentFrame, intentar cerrar desde la ventana contenedora
            javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
        }
    }//GEN-LAST:event_backButtonActionPerformed

    private void tipoEnvioComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoEnvioComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoEnvioComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JSpinner cantidadProductoVentasField;
    private javax.swing.JTextField celularField;
    private javax.swing.JTextField dniField;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField nombreField;
    private javax.swing.JButton registrarPedidoButton;
    private javax.swing.JComboBox<String> skuProductoVentasCombo;
    private javax.swing.JComboBox<String> tipoEnvioCombo;
    // End of variables declaration//GEN-END:variables
}
