/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

/**
 *
 * @author kelvincitopkmz
 */
public class CreateProductView extends javax.swing.JInternalFrame {

    /**
     * Creates new form CreateProductView
     */
    private controllers.CreateProductViewController controller;
    private controllers.DashboardViewController dashboardController;
    private javax.swing.JFrame parentFrame;

    public CreateProductView() {
        initComponents();
    controller = new controllers.CreateProductViewController();
    controller.initialize();
    }

    public void setParentFrame(javax.swing.JFrame frame) {
        this.parentFrame = frame;
    }

    public void setDashboardController(controllers.DashboardViewController dashboardController) {
    this.dashboardController = dashboardController;
    
    // Pasar también al CreateProductViewController
    if (controller != null) {
        controller.setDashboardController(dashboardController);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cantidadInvField2 = new javax.swing.JSpinner();
        jLabel27 = new javax.swing.JLabel();
        skuInvField = new javax.swing.JTextField();
        nombreInvField = new javax.swing.JTextField();
        precioInvField = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        registrarProductoButton = new javax.swing.JButton();

        jLabel24.setText("SKU");

        jLabel25.setText("Nombre");

        jLabel26.setText("Cantidad");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setText("Registrar nuevo producto");

        jLabel28.setText("Precio");

        backButton.setText("Volver");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        registrarProductoButton.setText("Registrar producto");
        registrarProductoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarProductoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addGap(131, 131, 131))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel28))
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cantidadInvField2)
                    .addComponent(skuInvField)
                    .addComponent(nombreInvField)
                    .addComponent(precioInvField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 115, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(registrarProductoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel27)
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(skuInvField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(nombreInvField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioInvField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(cantidadInvField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(registrarProductoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:

        if (parentFrame != null) {
            parentFrame.dispose();
        }
    }//GEN-LAST:event_backButtonActionPerformed

    private void registrarProductoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarProductoButtonActionPerformed
        // TODO add your handling code here:

        if (controller == null) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Error: Controller no inicializado",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    String sku = skuInvField.getText();
    String nombre = nombreInvField.getText();
    String precio = precioInvField.getText();
    int cantidad = (Integer) cantidadInvField2.getValue();

    boolean exitoso = controller.registrarProducto(sku, nombre, precio, cantidad);

    if (exitoso) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Producto registrado exitosamente",
                "Éxito",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );

        skuInvField.setText("");
        nombreInvField.setText("");
        precioInvField.setText("");
        cantidadInvField2.setValue(0);
        skuInvField.requestFocus();

        // Actualizar tabla de inventario
        if (dashboardController != null) {
            dashboardController.actualizarTablaInventario();
            dashboardController.actualizarTablaConteoInventario();
            // NUEVO: Actualizar combo de productos
            dashboardController.actualizarComboProductos();
        }

    } else {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Error al registrar el producto. Verifica que el SKU no exista.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_registrarProductoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JSpinner cantidadInvField2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField nombreInvField;
    private javax.swing.JTextField precioInvField;
    private javax.swing.JButton registrarProductoButton;
    private javax.swing.JTextField skuInvField;
    // End of variables declaration//GEN-END:variables
}
