/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

/**
 *
 * @author kelvincitopkmz
 */
public class EditarInfoEnvioView extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditarInfoEnvíoView
     */
    private controllers.EditarInfoEnvioViewController controller;
    private controllers.DashboardViewController dashboardController;
    private javax.swing.JFrame parentFrame;

    public EditarInfoEnvioView() {
        initComponents();
        controller = new controllers.EditarInfoEnvioViewController();
        controller.initialize();
    }

    /**
     * Establece el frame padre para poder cerrarlo
     */
    public void setParentFrame(javax.swing.JFrame frame) {
        this.parentFrame = frame;
    }

    /**
     * Establece el dashboard controller
     */
    public void setDashboardController(controllers.DashboardViewController dashboardController) {
        this.dashboardController = dashboardController;

        if (controller != null) {
            controller.setDashboardController(dashboardController);
        }
    }

    /**
     * Carga un pedido para editar su información de envío
     */
    public void cargarPedido(int nroOrden) {
        if (controller.cargarPedido(nroOrden)) {
            models.Pedido pedido = controller.getPedidoActual();
            models.InfoEnvio envio = pedido.getEnvio();

            // Cargar información de envío (dirección)
            if (envio != null) {
                depField.setText(envio.getDepartamento() != null ? envio.getDepartamento() : "");
                provField.setText(envio.getProvincia() != null ? envio.getProvincia() : "");
                distField.setText(envio.getDistrito() != null ? envio.getDistrito() : "");
                dirField.setText(envio.getDireccion() != null ? envio.getDireccion() : "");

                // Cargar información de tracking
                transField.setText(envio.getTransportadora() != null ? envio.getTransportadora() : "");
                sucField.setText(envio.getSucursal() != null ? envio.getSucursal() : "");
                ntrackField.setText(envio.getnTracking() != null ? envio.getnTracking() : "");
                ctrackField.setText(envio.getcTracking() != null ? envio.getcTracking() : "");
            }

            System.out.println("Información de envío cargada en la vista");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        depField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        provField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        distField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        dirField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        transField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        sucField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        ntrackField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        ctrackField = new javax.swing.JTextField();
        updateInfoEnvioButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Cambiar información de envío");

        jLabel8.setText("Departamento");

        jLabel9.setText("Provincia");

        jLabel10.setText("Distrito");

        jLabel18.setText("Dirección");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Cambiar información de tracking");

        jLabel20.setText("Transportadora");

        jLabel21.setText("Sucursal");

        jLabel22.setText("Número de tracking");

        jLabel23.setText("Código de tracking");

        updateInfoEnvioButton.setText("Actualizar datos");
        updateInfoEnvioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInfoEnvioButtonActionPerformed(evt);
            }
        });

        backButton.setText("Volver");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel22)
                                        .addComponent(jLabel23))
                                    .addGap(35, 35, 35)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(transField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(sucField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ctrackField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ntrackField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addComponent(jLabel19)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(27, 27, 27))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel18))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(depField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(provField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dirField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(distField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(updateInfoEnvioButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(depField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(provField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(distField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(dirField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(transField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(sucField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(ntrackField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(ctrackField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(updateInfoEnvioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateInfoEnvioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInfoEnvioButtonActionPerformed

        if (controller == null) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Error: Controller no inicializado",
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE
        );
        return;
    }
    
    // Validar que el pedido puede editar info de envío
    if (!controller.puedeEditarEnvio()) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Este pedido no puede editar su información de envío",
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE
        );
        return;
    }
    
    // Obtener datos del formulario
    String departamento = depField.getText();
    String provincia = provField.getText();
    String distrito = distField.getText();
    String direccion = dirField.getText();
    
    String transportadora = transField.getText();
    String sucursal = sucField.getText();
    String nroTracking = ntrackField.getText();
    String codTracking = ctrackField.getText();
    
    // Actualizar información de envío
    if (!controller.actualizarInfoEnvio(departamento, provincia, distrito, direccion)) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Error al actualizar la información de envío.\nVerifica que todos los campos estén completos.",
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE
        );
        return;
    }
    
    // Actualizar información de tracking
    controller.actualizarInfoTracking(transportadora, sucursal, nroTracking, codTracking);
    
    // Guardar cambios
    if (controller.guardarCambios()) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Información de envío actualizada exitosamente",
            "Éxito",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
        );
        
        // Cerrar la ventana
        if (parentFrame != null) {
            parentFrame.dispose();
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Error al guardar la información de envío",
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_updateInfoEnvioButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        
        if (parentFrame != null) {
        parentFrame.dispose();
    }
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField ctrackField;
    private javax.swing.JTextField depField;
    private javax.swing.JTextField dirField;
    private javax.swing.JTextField distField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField ntrackField;
    private javax.swing.JTextField provField;
    private javax.swing.JTextField sucField;
    private javax.swing.JTextField transField;
    private javax.swing.JButton updateInfoEnvioButton;
    // End of variables declaration//GEN-END:variables
}
