/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

/**
 *
 * @author kelvincitopkmz
 */
public class PaymentInfoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form PaymentInfoView
     */
    
    private controllers.PaymentInfoViewController controller;
private controllers.DashboardViewController dashboardController;
private javax.swing.JFrame parentFrame;
    
    public PaymentInfoView() {
        initComponents();
    controller = new controllers.PaymentInfoViewController();
    controller.initialize();
    }
    
    /**
 * Establece el frame padre para poder cerrarlo
 */
public void setParentFrame(javax.swing.JFrame frame) {
    this.parentFrame = frame;
}

/**
 * Establece el dashboard controller
 */
public void setDashboardController(controllers.DashboardViewController dashboardController) {
    this.dashboardController = dashboardController;
    
    if (controller != null) {
        controller.setDashboardController(dashboardController);
    }
}

/**
     * Carga un pedido para ver su información de pago
     */
    public void cargarPedido(int nroOrden) {
        if (controller.cargarPedido(nroOrden)) {
            models.Pedido pedido = controller.getPedidoActual();
            models.InfoPago pago = pedido.getPago();
            
            // Calcular saldo restante
            double saldoRestante = controller.calcularSaldoRestante();
            double adelanto = (pago != null) ? pago.getAdelanto() : 0.0;
            
            // Mostrar información en los campos
            // (ajusta los nombres según tus componentes: ctrackField y ctrackField1)
            ctrackField.setText(String.format("%.2f", adelanto));
            ctrackField1.setText(String.format("%.2f", saldoRestante));
            
            // Deshabilitar campos para solo lectura
            ctrackField.setEditable(false);
            ctrackField1.setEditable(false);
            
            System.out.println("Información de pago cargada - Adelanto: S/ " + adelanto + ", Saldo: S/ " + saldoRestante);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        ctrackField = new javax.swing.JTextField();
        ctrackField1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        registerPayButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Información de pago");

        jLabel23.setText("Pagado:");

        jLabel24.setText("Saldo restante:");

        registerPayButton.setText("REGISTRAR PAGO COMPLETO");
        registerPayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerPayButtonActionPerformed(evt);
            }
        });

        backButton.setText("Volver");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(ctrackField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel24)
                            .addGap(18, 18, 18)
                            .addComponent(ctrackField1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(registerPayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(ctrackField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(ctrackField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(registerPayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(backButton)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerPayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerPayButtonActionPerformed
        if (controller == null) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Error: Controller no inicializado",
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE
        );
        return;
    }
    
    // Validar que el pedido puede editar info de pago
    if (!controller.puedeEditarPago()) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Este pedido no puede modificar su información de pago",
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE
        );
        return;
    }
    
    // Obtener información del pedido
    models.Pedido pedido = controller.getPedidoActual();
    double precioTotal = pedido.getPrecio();
    double costoEnvio = pedido.calcularCostoEnvio(); // ✅ Strategy
    double montoTotal = precioTotal + costoEnvio;
    
    // Confirmar acción
    int confirmar = javax.swing.JOptionPane.showConfirmDialog(
        this,
        String.format("¿Estás seguro de registrar el pago completo?\n\n" +
                     "Precio del producto: S/ %.2f\n" +
                     "Costo de envío (%s): S/ %.2f\n" +
                     "MONTO TOTAL: S/ %.2f",
                     precioTotal, 
                     pedido.getTipoEnvio(),
                     costoEnvio, 
                     montoTotal),
        "Confirmar pago completo",
        javax.swing.JOptionPane.YES_NO_OPTION,
        javax.swing.JOptionPane.QUESTION_MESSAGE
    );
    
    if (confirmar != javax.swing.JOptionPane.YES_OPTION) {
        return;
    }
    
    // Registrar pago completo
    if (controller.registrarPagoCompleto() && controller.guardarCambios()) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            String.format("Pago completo registrado exitosamente\n\nMonto pagado: S/ %.2f", montoTotal),
            "Éxito",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
        );
        
        // Recargar información
        cargarPedido(controller.getPedidoActual().getOrden());
        
        // Cerrar la ventana después de registrar el pago
        if (parentFrame != null) {
            parentFrame.dispose();
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Error al registrar el pago completo",
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_registerPayButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        
        if (parentFrame != null) {
        parentFrame.dispose();
    }
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField ctrackField;
    private javax.swing.JTextField ctrackField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton registerPayButton;
    // End of variables declaration//GEN-END:variables
}
